"""add_portfolio_history_table

Revision ID: b971dbc637c7
Revises: 3acad58a6e91
Create Date: 2025-10-27 16:23:48.901542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b971dbc637c7'
down_revision = '3acad58a6e91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('position_value', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('pnl_percent', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_history_model_name'), 'portfolio_history', ['model_name'], unique=False)
    op.create_index(op.f('ix_portfolio_history_timestamp'), 'portfolio_history', ['timestamp'], unique=False)
    op.add_column('strategy_configs', sa.Column('max_position_percent', sa.Float(), nullable=True))
    op.add_column('strategy_configs', sa.Column('take_profit_percent', sa.Float(), nullable=True))
    op.drop_column('strategy_configs', 'params')
    op.drop_column('strategy_configs', 'max_position_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy_configs', sa.Column('max_position_size', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('strategy_configs', sa.Column('params', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('strategy_configs', 'take_profit_percent')
    op.drop_column('strategy_configs', 'max_position_percent')
    op.drop_index(op.f('ix_portfolio_history_timestamp'), table_name='portfolio_history')
    op.drop_index(op.f('ix_portfolio_history_model_name'), table_name='portfolio_history')
    op.drop_table('portfolio_history')
    # ### end Alembic commands ###

